# Generated by Django 4.1.2 on 2022-10-16 07:36

import backend.modelUtils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('abstract', models.TextField(blank=True, default='')),
                ('details', models.TextField(blank=True, default='')),
                ('demoURL', models.TextField(blank=True, default='#')),
                ('codeURL', models.TextField(blank=True, default='#')),
                ('videoURL', models.TextField(blank=True, default='#')),
                ('hasVideo', models.BooleanField(default=False)),
                ('isFeatured', models.BooleanField(default=False)),
                ('album', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model', to='backend.imagealbum')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ANGULAR', 'Angular'), ('CSS', 'Css'), ('PYTHON', 'Python'), ('DJANGO', 'Django'), ('GIT', 'Git'), ('HTML', 'Html'), ('TYPESCRIPT', 'Typescript'), ('UBUNTU', 'Ubuntu')], default='ANGULAR', max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='backend.project')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=backend.modelUtils.get_upload_path)),
                ('default', models.BooleanField(default=False)),
                ('width', models.FloatField(default=100)),
                ('height', models.FloatField(default=100)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='backend.imagealbum')),
            ],
        ),
    ]
