# Generated by Django 4.1.2 on 2022-10-16 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='album',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model', to='backend.imagealbum'),
        ),
    ]
