# Generated by Django 4.1.2 on 2022-10-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_project_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='showcase',
            field=models.BooleanField(default=False),
        ),
    ]
