# Generated by Django 4.1.2 on 2024-06-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_resume_showcase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
