# Generated by Django 4.1.2 on 2024-07-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_project_options_project_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='tech_skills',
            field=models.ManyToManyField(related_name='projects', to='backend.skill'),
        ),
        migrations.AddField(
            model_name='skill',
            name='imageURL',
            field=models.URLField(default='#'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
