# Generated by Django 4.1.2 on 2024-07-27 01:09

from django.db import migrations
from backend.enums import TechIcon

def add_skill_data(apps, schema_editor):
    Skill = apps.get_model('backend', 'Skill')
    for icon in TechIcon:
        Skill.objects.create(name=icon.label, imageURL=icon.url)

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_skill_project_project_tech_skills_and_more'),
    ]

    operations = [
      migrations.RunPython(add_skill_data),
    ]
